import { Alert } from '../models/Alert.js';
import { nextId } from '../utils/sequence.js';
import { config } from '../config/index.js';
import { SOCKET_EVENTS, SOURCES, SEVERITIES, CATEGORIES, SCENARIOS } from '../utils/constants.js';
import {
  rnd, pick, chance, intIP, privIP, randHash,
  HOSTS, BAD_DOMAINS, BAD_URLS, randUser,
} from '../utils/random.js';

// Per-source realistic raw log line.
function rawFor(source, category, ctx) {
  const { srcIp, host, user, domain, url } = ctx;
  switch (source) {
    case 'Firewall':
      return `DENY proto=TCP src=${srcIp} dst=${privIP()} spt=${rnd(1024, 65535)} dpt=${pick([22, 23, 445, 3389, 8080])} action=block`;
    case 'IDS/IPS':
      return `[**] [1:${rnd(1000, 9999)}:5] ${category} signature match [**] {TCP} ${srcIp} -> ${privIP()}`;
    case 'EDR':
      return `process=powershell.exe parent=winword.exe host=${host} user=${user} cmdline="-enc ${randHash().slice(0, 24)}" verdict=suspicious`;
    case 'Win Event Log':
      return `EventID=${pick([4625, 4672, 4688, 4720])} host=${host} account=${user} logontype=${pick([3, 10])} status=0x${rnd(10, 99)}`;
    case 'Linux Log':
      return `sshd[${rnd(1000, 9999)}]: Failed password for ${user} from ${srcIp} port ${rnd(1024, 65535)} ssh2`;
    case 'DNS Log':
      return `query: ${domain} type=A client=${privIP()} response=NXDOMAIN flags=rd`;
    case 'Proxy Log':
      return `${srcIp} CONNECT ${domain}:443 url="https://${domain}${url}" bytes=${rnd(1024, 5_000_000)} cat=uncategorized`;
    case 'Cloud Log':
      return `eventName=${pick(['GetObject', 'PutObject', 'AssumeRole', 'ConsoleLogin'])} principal=${user} sourceIP=${srcIp} result=${pick(['Success', 'Failure'])}`;
    default:
      return `${source} event for ${host}`;
  }
}

function titleFor(category, source) {
  return `${category} indicator observed via ${source}`;
}

// Build (but do not persist) one alert payload.
async function buildAlert(opts = {}) {
  const source = opts.source || pick(SOURCES);
  const category = opts.category || pick(CATEGORIES);
  const severity = opts.severity || pick(SEVERITIES);
  const srcIp = opts.srcIp || intIP();
  const host = opts.host || pick(HOSTS);
  const user = opts.user || randUser();
  const domain = opts.domain || pick(BAD_DOMAINS);
  const url = opts.url || pick(BAD_URLS);
  const hash = chance(0.5) ? randHash() : undefined;

  const ctx = { srcIp, host, user, domain, url };
  const alertId = await nextId('ALR', 5);

  return {
    alertId,
    source,
    category,
    severity,
    title: opts.title || titleFor(category, source),
    raw: rawFor(source, category, ctx),
    srcIp,
    destIp: privIP(),
    host,
    user,
    domain,
    url,
    hash,
    status: 'New',
    scenario: opts.scenario || null,
    mitre: opts.mitre || [],
    stage: 0,
    detectMin: +(Math.random() * 8 + 0.5).toFixed(1),
    iocs: {
      ip: [srcIp],
      domain: [domain],
      url: [url],
      hash: hash ? [hash] : [],
    },
    timeline: [{ at: new Date(), text: `Alert generated by ${source}`, actor: 'SIEM Engine' }],
  };
}

// Persist a single alert and emit it over Socket.IO.
export async function createAlert(io, opts = {}) {
  const payload = await buildAlert(opts);
  const alert = await Alert.create(payload);
  if (io) io.emit(SOCKET_EVENTS.ALERT_NEW, alert);
  return alert;
}

// Inject a correlated attack chain sharing IOCs (host, srcIp, user, domain).
export async function runScenario(io, key) {
  const sc = SCENARIOS[key];
  if (!sc) throw Object.assign(new Error(`Unknown scenario "${key}"`), { status: 400 });

  const sharedIp = intIP();
  const sharedHost = pick(HOSTS);
  const sharedUser = randUser();
  const sharedDom = pick(BAD_DOMAINS);
  const chain = [];

  for (let i = 0; i < sc.steps.length; i += 1) {
    const isLast = i === sc.steps.length - 1;
    // eslint-disable-next-line no-await-in-loop
    const alert = await createAlert(io, {
      source: sc.steps[i],
      category: sc.cat,
      severity: isLast ? sc.sev : pick(['Medium', 'High']),
      mitre: sc.mitre,
      scenario: sc.name,
      srcIp: sharedIp,
      host: sharedHost,
      user: sharedUser,
      domain: sharedDom,
      title: `[${sc.name}] ${titleFor(sc.cat, sc.steps[i])}`,
    });
    chain.push(alert);
  }
  return chain;
}

// Background timer that periodically generates ambient alerts (demo mode).
let timer = null;

export function startAlertEngine(io) {
  if (!config.alertEngine.enabled || timer) return;
  timer = setInterval(() => {
    const burst = rnd(1, 3);
    for (let i = 0; i < burst; i += 1) {
      // occasionally fire a full correlated scenario
      if (chance(0.12)) {
        runScenario(io, pick(Object.keys(SCENARIOS))).catch(() => {});
      } else {
        createAlert(io).catch(() => {});
      }
    }
  }, config.alertEngine.intervalMs);
  // eslint-disable-next-line no-console
  console.log(`[engine] alert engine started (every ${config.alertEngine.intervalMs}ms)`);
}

export function stopAlertEngine() {
  if (timer) clearInterval(timer);
  timer = null;
}
